### ISSUE TITLE
Add link to the floating menu

### ISSUE THREAD

**Issue by Daniel15** [splitbrain/dokuwiki-plugin-talkpage#2]
Maybe the "discussion" link should be added to the floating menu where Edit This Page, Old Revisions, etc. are

**Comment by dinobib** [comment]
I have followed these advice and it works great. 
In my template I wish to present the pagetools differently and so need to move it eleswhere in the template. 
All classic pagetools actions still works without problem but the talk page button didn’t work now (the url doesn’t output the talk namespace and the button doesn’t  recognize if the page exist or not or if we are on it).
In main.php of template, my need is to move the pageaction before the getting the content via `<?php tpl_content(false)?>`.
I think this is the problem and it change the context which prevent the talk button action to stop working correctly. 
How could I deal with this? How could pageaction could have the correct context but in html before getting the content?

**Comment by dinobib** [comment]
Ok I have made it work,
It could be before `tpl_content` but need to be inside the `<div id="dokuwiki__content"><div class="pad group">`. 
I don’t know why but it works that way.

**Comment by dinobib** [comment]
Anybody have an idea ? 
I wish to display the pagetools in the sidebar but the talk button doesn't work there.
I just don't get what coud prevent it to work there.
What could have change in term of context ? and what could be done to make this work ?

**Comment by nallison** [comment]
Hi @dinobib,

I am sorry but I have not  done any work customising Dokuwiki since 2012 when I used release "Adora Belle".  There are several releases since then and I so I cannot be of more assistance at this time.  Perhaps someone else will have some hints to help you.

Kind regards,
Neil,
Christchurch, NZ

**Comment by dinobib** [comment]
Hi @nallison 
Thanks for your words.
I am using the last contribution of @martinb1-GIT with the last Dokuwiki. It works great but I made a lot of custom work on it (changing from the fier popup to a regular list and using iconfont instead of images).
The only things that doesn't work is when I place it in the sidebar (which is what I wish) as all page tools button works but not the talk one. 
So the problem would be in the last code of @martinb1-GIT but I can't see what could cause this behaviour. What variable or context isn't right when the code is called from the sidebar.
Best.
